2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Configure stats pid to 458251
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Loading settings from /home/sasuke/.config/wandb/settings
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Loading settings from /home/sasuke/repos/CS6910/Assignment-1/wandb/settings
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'Assignment-1/train.py', 'program': 'train.py'}
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_init.py:_log_setup():492] Logging user logs to /home/sasuke/repos/CS6910/Assignment-1/wandb/run-20230317_165426-lzvdm7xc/logs/debug.log
2023-03-17 16:54:26,702 INFO    MainThread:458251 [wandb_init.py:_log_setup():493] Logging internal logs to /home/sasuke/repos/CS6910/Assignment-1/wandb/run-20230317_165426-lzvdm7xc/logs/debug-internal.log
2023-03-17 16:54:26,703 INFO    MainThread:458251 [wandb_init.py:init():532] calling init triggers
2023-03-17 16:54:26,703 INFO    MainThread:458251 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 16:54:26,703 INFO    MainThread:458251 [wandb_init.py:init():588] starting backend
2023-03-17 16:54:26,703 INFO    MainThread:458251 [wandb_init.py:init():592] setting up manager
2023-03-17 16:54:26,707 INFO    MainThread:458251 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-17 16:54:26,710 INFO    MainThread:458251 [wandb_init.py:init():599] backend started and connected
2023-03-17 16:54:26,715 INFO    MainThread:458251 [wandb_init.py:init():687] updated telemetry
2023-03-17 16:54:26,752 INFO    MainThread:458251 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-17 16:54:33,476 INFO    MainThread:458251 [wandb_run.py:_on_init():2134] communicating current version
2023-03-17 16:54:33,667 INFO    MainThread:458251 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-17 16:54:33,667 INFO    MainThread:458251 [wandb_init.py:init():775] starting run threads in backend
2023-03-17 16:54:45,285 INFO    MainThread:458251 [wandb_run.py:_console_start():2114] atexit reg
2023-03-17 16:54:45,285 INFO    MainThread:458251 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-17 16:54:45,285 INFO    MainThread:458251 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-17 16:54:45,285 INFO    MainThread:458251 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-17 16:54:45,286 INFO    MainThread:458251 [wandb_init.py:init():817] run started, returning control to user process
2023-03-17 16:55:24,628 INFO    MainThread:458251 [wandb_run.py:_config_callback():1250] config_cb ('_wandb', 'visualize', 'mse vs crossentropy') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/lineseries/v0', 'fieldSettings': {'step': 'step', 'lineKey': 'lineKey', 'lineVal': 'lineVal'}, 'stringSettings': {'title': 'mse vs cross_entropy', 'xname': 'epochs'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'mse vs crossentropy_table'}], 'fields': []}]}]}}} None
2023-03-17 16:56:47,768 WARNING MsgRouterThr:458251 [router.py:message_loop():77] message_loop has been closed
